### ISSUE TITLE
I need libttsespeak.so

### ISSUE THREAD

**Issue by amorenew** [rhdunn/espeak#116]
I got error on Android because `librrsespeak.so` is missing

```
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList
[[zip file "/data/app/com.reecedunn.espeak-dLLT48opPq9KYthFf6LLjQ==/base.apk"],
nativeLibraryDirectories=
[/data/app/com.reecedunn.espeak-dLLT48opPq9KYthFf6LLjQ==/lib/x86, /system/lib, /vendor/lib]]]
 couldn't find "libttsespeak.so"
    at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
    at java.lang.System.loadLibrary(System.java:1657)
    at com.reecedunn.espeak.SpeechSynthesis.<clinit>(SpeechSynthesis.java:56)
    at com.reecedunn.espeak.SpeechSynthesis.getVoiceCount(SpeechSynthesis.java:90)
```

Could you provide this file?
it's not pushed because it is in the `.gitignore` file

**Comment by rhdunn** [comment]
It is excluded in `.gitignore` because it is a build artefact. See https://github.com/rhdunn/espeak#building-with-gradle.

Is your android system running in 64-bits only mode? You will need to modify https://github.com/rhdunn/espeak/blob/master/android/jni/Application.mk to build the 64-bit version of that library if that is the case.
