### ISSUE TITLE
Possible Kirshenbaum / IPA  quirks and glitches?

### ISSUE THREAD

**Issue by cmrdt** [rhdunn/espeak#97]
(en-us)
short `[A]` is missing..
also `[y-]` (same as `[i]`) does not produce anything (if encounters character it cant handle, it quits the rest, & lack of error info)
but does this right
`[@r]`  turns into ɚr  
thus are glitches context-based?
```
io	ɪo
i:o	iːo
I	i
@t@	əɾˈə
```

`espeak-ng -X  --tie --ipa`
ASCII, [t_vowel] [t_vowel-long] [t_vowel_t]
ASCII,  [consonant] [@_consonant_@]
and trimming the results:

```
i	i	iː	i
y			
i"	i	i	i
u"	u	u	u
u-	u	uː	u
u	u	uː	u
I	i	iː	ɪ
I.	i	i	i
U-	ʊ	ʊː	ʊ
U	ʊ	ʊː	ʊ
e	e	eː	e
Y			
@<umd>	ə	ə	ə
@.	ə	ə	ə
o-	o	oː	o
o	o	oː	o
R<umd>	r	r	r
@	ə	əː	ə
R	r	rr	r
E	ɛ	ɛː	ɛ
W			
V"	ʌ	ʌ	ʌ
O"	ɔ	ɔ	ɔ
V	ʌ	ʌː	ʌ
O	ɔ	ɔː	ɔ
&			
&"			
a.	æ	æ	æ
a"	æ	æ	æ
A".			
A		ɑː	
A.			
```

```
m	m	m
M		
n	n	n
n	n	n
n.	ɳ	ɳ
n^	ɲ	ɲ
N	ŋ	ŋ
n"	n	n
n<lbv>	n	n
p	p	p
b	b	b
t	t̪	t̪
d	d̪	d̪
t	t	ɾ
d	d	d
t.	t	t
d.	d	d
c	c	c
J	ɟ	ɟ
k	k	k
g	ɡ	ɡ
q	q	q
G		
t<lbv>	t	t
d<lbv>	d	d
?	ʔ	ʔ
P		
B	β	β
f	f	f
v	v	v
T	θ	θ
D	ð	ð
s	s	s
z	z	z
s.	ʂ	ʂ
z.	ʐ	ʐ
S	ʃ	ʃ
Z	ʒ	ʒ
C	ç	ç
C<vcd>	ç	ç
x	x	x
Q	ɣ	ɣ
X	χ	χ
g"	ɡ	ɡ
w<vls>	w	w
w	w	w
H		
H<vcd>		
h<?>	h	h
s<lat>	s	s
z<lat>	z	z
r<lbd>	r	r
r	r	r
r	r	ɹ
r.	r.	r.
j	j	j
j<vel>	j	j
g"	ɡ	ɡ
w	w	w
h	h	h
l	l	l
l	l	l
l.	ɭ	ɭ
l^	ʎ	ʎ
L	ɫ	͡l
b<trl>	b	b
r<trl>	r	r
r"	ʀ	ʀ
  *		
  *.		
*<lat>	ɾ	ɾ
p`	p	p
t`	t̪	t̪
t`	t	t
c`	c	c
k`	k	k
q`	q	q
b`	b	b
d`	d	d
d`	d	d
J`	ɟ	ɟ
g`	ɡ	ɡ
G`		
p!	p	p
t!	t	t
c!	c	c
c!	c	c
k!	k	k
l!	l	l
```

**Comment by cmrdt** [comment]
whether to change gradual espeak's internal workings to more  IPA based

**Comment by rhdunn** [comment]
See:
1.  https://github.com/espeak-ng/espeak-ng/issues/25 -- Create a "jonathan" voice from the existing phoneme table data
2.  https://github.com/espeak-ng/espeak-ng/issues/26 -- Support phoneme transcriptions in the phoneme definitions
3.  https://github.com/espeak-ng/espeak-ng/issues/27 -- Support phoneme input modes

The `[A]` vowel is not supported in English because eSpeak uses `[A:]` for the `PALM` vowel. It also transforms the given phoneme input based on the specific language rules, which is why what you specify phonetically is not necessarily what is spoken/output.
